CREATE TABLE "SCOTT"."TELE_GRAF_ALERTS" 
   (	"ALERT_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"RAW_METRICS" VARCHAR2(4000 BYTE), 
	"AI_ANALYSIS" CLOB, 
	 CONSTRAINT "PK_TELE_GRAF_ALERTS" PRIMARY KEY ("ALERT_TIME");