CREATE TABLE "SCOTT"."TELE_GRAF_ALL" 
   (	"END_TIME" DATE, 
	"T_USERIO" NUMBER, 
	"T_CONCURRENCY" NUMBER, 
	"T_SYSTEMIO" NUMBER, 
	"T_COMMIT" NUMBER, 
	"T_NETWORK" NUMBER, 
	"T_APPLICATION" NUMBER, 
	"T_CONFIGURATION" NUMBER, 
	"T_ADMINISTRATIVE" NUMBER, 
	"P_USERIO" NUMBER, 
	"P_CONCURRENCY" NUMBER, 
	"P_SYSTEMIO" NUMBER, 
	"P_COMMIT" NUMBER, 
	"P_NETWORK" NUMBER, 
	"P_APPLICATION" NUMBER, 
	"P_CONFIGURATION" NUMBER, 
	"P_ADMINISTRATIVE" NUMBER
   );